#!/usr/bin/env python3
import argparse
import os
import re
from pathlib import Path

import pandas as pd


PREFERRED_COLS = [
    "split",
    "length",
    "auto_answer_acc",
    "auto_code_acc",
    "expected_exit_step",
    "argmax_exit_step_mean",
    "argmax_exit_step_mode",
    "best_forced_answer_acc",
    "best_forced_answer_step",
    "min_answer_step_loss",
    "min_answer_loss_step",
    "auto_acc_answer",
    "auto_acc_code",
    "best_forced_acc_answer",
    "best_forced_step",
]


def norm_pe(x):
    return str(x).strip().lower()


def parse_bits_from_row(row):
    wb = row.get("weight_bits", None)
    if pd.notna(wb):
        try:
            return int(float(wb))
        except Exception:
            pass

    q = str(row.get("quant_tag", "")).lower()
    if "fp32" in q:
        return 32

    m = re.search(r"wbits(\d+)", q)
    if m:
        return int(m.group(1))

    return None


def seed_equal(x, seed):
    if pd.isna(x):
        return False
    try:
        return int(float(x)) == int(seed)
    except Exception:
        return str(x).strip() == str(seed)


def safe_float_seed(seed):
    try:
        return int(float(seed))
    except Exception:
        return seed


def choose_latest(sub):
    sub = sub.copy()

    def mtime(p):
        try:
            return os.path.getmtime(str(p))
        except Exception:
            return -1

    sub["_mtime"] = sub["summary_csv"].apply(mtime)
    sub = sub.sort_values(["_mtime", "run_id"], ascending=[True, True])
    return sub.iloc[-1], len(sub)


def format_table(df):
    cols = [c for c in PREFERRED_COLS if c in df.columns]
    rest = [c for c in df.columns if c not in cols]
    if cols:
        df = df[cols + rest]

    if "length" in df.columns:
        df["length"] = pd.to_numeric(df["length"], errors="ignore")

    return df.to_string(index=False)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--index",
        type=str,
        required=True,
        help="Run index CSV generated by summarize_precision_results.py",
    )
    parser.add_argument(
        "--outdir",
        type=str,
        default="../reports/precision_ponder_seed_results",
        help="Directory for exported txt files",
    )
    parser.add_argument(
        "--seed",
        type=str,
        required=True,
        help="Seed to export, e.g. 1",
    )
    parser.add_argument(
        "--pes",
        type=str,
        nargs="+",
        default=["nope", "rope"],
        help="PE list, e.g. nope rope",
    )
    parser.add_argument(
        "--bits",
        type=int,
        nargs="+",
        default=[32, 16, 8],
        help="Bits list, e.g. 32 16 8",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing txt files",
    )
    args = parser.parse_args()

    index_path = Path(args.index)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    idx = pd.read_csv(index_path)

    required = ["summary_csv", "run_id", "run_dir", "pe"]
    missing = [c for c in required if c not in idx.columns]
    if missing:
        raise ValueError(f"Missing columns in run index: {missing}")

    idx["_pe_norm"] = idx["pe"].apply(norm_pe)
    idx["_bits"] = idx.apply(parse_bits_from_row, axis=1)

    seed_tag = f"seed{safe_float_seed(args.seed)}"

    exported = []
    skipped = []

    for pe in args.pes:
        pe_norm = norm_pe(pe)

        for bits in args.bits:
            sub = idx[
                (idx["_pe_norm"] == pe_norm)
                & (idx["_bits"] == int(bits))
                & (idx["seed"].apply(lambda x: seed_equal(x, args.seed)))
            ].copy()

            out_name = f"{pe_norm}_copy_ponder_bits{bits}_{seed_tag}.txt"
            out_path = outdir / out_name

            if len(sub) == 0:
                skipped.append((out_name, "no matching run"))
                continue

            chosen, n_match = choose_latest(sub)
            summary_csv = Path(str(chosen["summary_csv"]))

            if not summary_csv.exists():
                skipped.append((out_name, f"summary_csv not found: {summary_csv}"))
                continue

            if out_path.exists() and not args.overwrite:
                skipped.append((out_name, "already exists; use --overwrite to replace"))
                continue

            df = pd.read_csv(summary_csv)

            header = []
            header.append(f"Latest Run: {chosen['run_id']}")
            header.append(f"Seed: {safe_float_seed(args.seed)}")
            header.append(f"PE: {pe_norm}")
            header.append(f"Bits: {bits}")
            header.append(f"Matched Runs: {n_match}")
            header.append(f"Run Dir: {chosen['run_dir']}")
            header.append(f"Summary CSV: {summary_csv}")
            header.append("-" * 120)

            body = format_table(df)

            text = "\n".join(header) + "\n" + body + "\n" + "-" * 120 + "\n"
            out_path.write_text(text, encoding="utf-8")

            exported.append(out_path)

    print("================================================================================")
    print(f"[export] seed={args.seed}")
    print(f"[export] outdir={outdir}")
    print("================================================================================")

    if exported:
        print("[exported]")
        for p in exported:
            print(f"  {p}")

    if skipped:
        print("\n[skipped]")
        for name, reason in skipped:
            print(f"  {name}: {reason}")


if __name__ == "__main__":
    main()
